

module StatesCodes
    def get_code_from_state(state_name)
        state_name_formatted = state_name.remove(" ").parameterize
        case state_name_formatted
            when "rondonia"
                return "RO"
            when "acre"
                return "AC"
            when "amazonas"
                return "AM"
            when "roraima"
                return "RR"
            when "para"
                return "PA"
            when "amapa"
                return "AP"
            when "tocantins"
                return "TO"
            when "maranhao"
                return "MA"
            when "piaui"
                return "PI"
            when "ceara"
                return "CE"
            when "riograndedonorte"
                return "RN"
            when "paraiba"
                return "PB"
            when "pernambuco"
                return "PE"
            when "alagoas"
                return "AL"
            when "sergipe"
                return "SE"
            when "bahia"
                return "BA"
            when "minasgerais"
                return "MG"
            when "espiritosanto"
                return "ES"
            when "riodejaneiro"
                return "RJ"
            when "saopaulo" 
                return "SP"
            when "parana"
                return "PR"
            when "santacatarina"
                return "SC"
            when "riograndedosul"
                return "RS"
            when "matogrossodosul"
                return "MS"
            when "matogrosso"
                return "MT"
            when "goias"
                return "GO"
            when "distritofederal"
                return "DF"
        end
    end
end